networks:
  k6:
  grafana:
  influxdb:
  kafka-net:
    driver: bridge


services:
  zookeeper-server:
    image: 'bitnami/zookeeper:latest'
    networks:
    - kafka-net
    ports:
    - '2181:2181'
    environment:
    - ALLOW_ANONYMOUS_LOGIN=yes
  broker:
    image: 'bitnami/kafka:latest'
    networks:
    - kafka-net
    ports:
    - '9092:9092'
    - '9094:9094'
    environment:
    - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181
    - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,EXTERNAL://:9094
    - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,EXTERNAL://broker:9094
    - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
    - ALLOW_PLAINTEXT_LISTENER=yes
    - KAFKA_CFG_CREATE_TOPICS=topic1:2:1,topic2:2:1
    depends_on:
    - zookeeper-server
  prometheus:
    image: prom/prometheus:latest
    networks:
      - kafka-net
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  influxdb:
    image: influxdb:2.0-alpine
    networks:
      - k6
      - grafana
      - influxdb
      - kafka-net
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=croco
      - DOCKER_INFLUXDB_INIT_PASSWORD=password1
      - DOCKER_INFLUXDB_INIT_ORG=k6io
      - DOCKER_INFLUXDB_INIT_BUCKET=demo
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=EEKpryGZk8pVDXmIuy484BKUxM5jOEDv7YNoeNZUbsNbpbPbP6kK_qY9Zsyw7zNnlZ7pHG16FYzNaqwLMBUz8g==
    volumes:
      - ./grafana:/etc/grafana/provisioning/
  grafana:
    image: grafana/grafana:8.2.6
    networks:
       - grafana
       - influxdb
       - kafka-net
    ports:
        - "3000:3000"
    environment:
        - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
        - GF_AUTH_ANONYMOUS_ENABLED=true
        - GF_AUTH_BASIC_ENABLED=false
    volumes:
        - ./grafana:/etc/grafana/provisioning/
  k6:
      build: .
      networks:
        - k6
        - kafka-net
      ports:
        - "6565:6565"
      environment:
        - K6_OUT=xk6-influxdb=http://influxdb:8086
        - K6_INFLUXDB_ORGANIZATION=k6io
        - K6_INFLUXDB_BUCKET=demo
        - K6_INFLUXDB_INSECURE=true
        # NOTE: This is an Admin token, it's not suggested to use this configuration in production.
        # Instead, use a Token with restricted privileges.
        - K6_INFLUXDB_TOKEN=EEKpryGZk8pVDXmIuy484BKUxM5jOEDv7YNoeNZUbsNbpbPbP6kK_qY9Zsyw7zNnlZ7pHG16FYzNaqwLMBUz8g==
      volumes:
        - ./scripts:/scripts

# 53kT-YeSMHHw7IfRU5GeehhXNDOMa396l2mjxtWjRzrJRVt9JBQc1vhGFktquyVfyzUf6hjY6G7rJPQZ5eEOhg==
# eaLgJ9zAL3bAvHHoZiDCpNrsDZGheNXXKAdg-FlP2o4kluOCaI_dYnJZqxlMtXzdY24C-OJg5SmfResgzno6ig==
# vihmR1-2L4l2SZ_GQ4SJi-qNFPr8Bv3ObrOG3vpKj3d908FbqzjSS8jdxhZybvFSmsTTLuLUQXAHDFgdSBqqlQ==